language: ruby
rvm:
  - "2.4"

before_install:
  - nvm install node

install:
  - npm install
  - bundle install

script:
  - npm run build:dist
  - bundle exec htmlproofer ./_site

deploy:
  provider: azure_web_apps

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
