language: ruby
rvm:
  - 2.3

before_install:
  - nvm install 0.12
  - nvm use 0.12
  - npm install -g grunt-cli

install:
  - bundle install
  - npm install

script:
  - grunt build
  - bundle exec htmlproofer ./_site --url-ignore linkedin.com

after_success:
  - chmod +x deploy.sh
  - ./deploy.sh
  
branches:
  only:
    - master

sudo: false
addons:
  apt:
    packages:
      - ncftp
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true