language: ruby
rvm:
  - "stable"

sudo: false
addons:
  apt:
    packages:
      - ncftp
      - libcurl3-dev

before_install:
  - nvm install node

install:
  - npm install
  - bundle install

script:
  - npm run build:dist
#  - bundle exec htmlproofer ./_site

after_success:
  - chmod +x deploy.sh
  - ./deploy.sh

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
