author: 
  name: 'Jamie Magee'
  url: 'https://jamiemagee.co.uk'
baseurl: /
description: 'Programmer, Engineer, All Round Nice Person'
github:
  repo: 'https://github.com/JamieMagee/jamiemagee.co.uk'
source: blog

highlighter: rouge
markdown: kramdown

plugins: [jekyll-paginate]
paginate: 5

permalink: pretty
tagline: 'Programmer, Engineer, All Round Nice Person'
title: Jamie Magee
url: 'https://jamiemagee.co.uk'

defaults:
  -
    scope:
      path: "_posts"
    values:
      comments: true
      layout: post

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []