author: 
  name: 'Jamie Magee'
  url: 'https://jamiemagee.co.uk'
baseurl: /
description: 'Programmer, Engineer, All Round Nice Person'
github:
  repo: 'https://github.com/JamieMagee/jamiemagee.co.uk'
highlighter: rouge
markdown: kramdown
exclude: ['img', 'css', 'js', 'fonts', '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']
future: true
show_drafts: true
gems: [jekyll-paginate]
paginate: 5
permalink: pretty
tagline: 'Programmer, Engineer, All Round Nice Person'
title: Jamie Magee
url: 'https://jamiemagee.co.uk'
exclude: ['LICENSE.md', 'Gemfile', 'script']